In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as sns
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.tree import DecisionTreeRegressor

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/sixphase/Top Indian Places to Visit.csv")
df

In [3]:
col = ['Type','Google review rating','Number of google review in lakhs','Entrance Fee in INR']
df = df[col]
df

Type  Google review rating  Number of google review in lakhs  \
0    War Memorial                   4.6                              2.60   
1            Tomb                   4.5                              0.40   
2          Temple                   4.6                              0.40   
3      Theme Park                   4.1                              0.27   
4     Observatory                   4.2                              0.31   
..            ...                   ...                               ...   
320        Temple                   4.6                              0.18   
321          Fort                   4.5                              1.30   
322        Museum                   4.7                              0.15   
323        Palace                   4.4                              0.51   
324        Museum                   4.5                              0.63   

     Entrance Fee in INR  
0                      0  
1                     30  
2                     60  
3                     50  
4                     15  
..                   ...  
320                    0  
321                   40  
322                   10  
323                  200  
324                  200  

[325 rows x 4 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 4 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Type                              325 non-null    object 
 1   Google review rating              325 non-null    float64
 2   Number of google review in lakhs  325 non-null    float64
 3   Entrance Fee in INR               325 non-null    int64  
dtypes: float64(2), int64(1), object(1)
memory usage: 10.3+ KB


In [5]:
df.describe()

Google review rating  Number of google review in lakhs  \
count            325.000000                        325.000000   
mean               4.486154                          0.408438   
std                0.274580                          0.646668   
min                1.400000                          0.010000   
25%                4.400000                          0.059000   
50%                4.500000                          0.170000   
75%                4.600000                          0.500000   
max                4.900000                          7.400000   

       Entrance Fee in INR  
count           325.000000  
mean            115.809231  
std             530.859785  
min               0.000000  
25%               0.000000  
50%               0.000000  
75%              40.000000  
max            7500.000000

In [6]:
df.isnull().sum()

Type                                0
Google review rating                0
Number of google review in lakhs    0
Entrance Fee in INR                 0
dtype: int64

In [7]:
df = df[df['Entrance Fee in INR']!=0]
df

Type  Google review rating  Number of google review in lakhs  \
1           Tomb                   4.5                              0.40   
2         Temple                   4.6                              0.40   
3     Theme Park                   4.1                              0.27   
4    Observatory                   4.2                              0.31   
7           Fort                   4.5                              1.50   
..           ...                   ...                               ...   
318       Museum                   4.4                              0.24   
321         Fort                   4.5                              1.30   
322       Museum                   4.7                              0.15   
323       Palace                   4.4                              0.51   
324       Museum                   4.5                              0.63   

     Entrance Fee in INR  
1                     30  
2                     60  
3                     50  
4                     15  
7                     35  
..                   ...  
318                   50  
321                   40  
322                   10  
323                  200  
324                  200  

[142 rows x 4 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 142 entries, 1 to 324
Data columns (total 4 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Type                              142 non-null    object 
 1   Google review rating              142 non-null    float64
 2   Number of google review in lakhs  142 non-null    float64
 3   Entrance Fee in INR               142 non-null    int64  
dtypes: float64(2), int64(1), object(1)
memory usage: 5.5+ KB


In [9]:
df.describe()

Google review rating  Number of google review in lakhs  \
count            142.000000                        142.000000   
mean               4.421127                          0.442229   
std                0.328511                          0.765387   
min                1.400000                          0.010000   
25%                4.400000                          0.082500   
50%                4.500000                          0.215000   
75%                4.600000                          0.507500   
max                4.900000                          7.400000   

       Entrance Fee in INR  
count           142.000000  
mean            265.056338  
std             779.569628  
min               5.000000  
25%              20.000000  
50%              50.000000  
75%             150.000000  
max            7500.000000

In [10]:
df['Type'].unique()

array(['Tomb', 'Temple', 'Theme Park', 'Observatory', 'Fort', 'Park',
       'Museum', 'Zoo', 'Monument', 'Science', 'National Park',
       'Amusement Park', 'Palace', 'Botanical Garden', 'Landmark',
       'Film Studio', 'Tombs', 'Cricket Ground', 'Waterfall',
       'Bird Sanctuary', 'Cultural', 'Lake', 'Wildlife Sanctuary',
       'Sculpture Garden', 'Cave', 'Mausoleum', 'Vineyard', 'Valley',
       'Temples', 'Site', 'Prehistoric Site', 'Adventure Sport',
       'Ski Resort', 'Orchard', 'Monastery', 'Memorial', 'Aquarium',
       'Hill', 'Religious Complex', 'Rock Carvings', 'Beach',
       'Natural Feature', 'Entertainment', 'Race Track'], dtype=object)

In [11]:
df['Type'].value_counts()

Fort                  17
National Park         14
Palace                11
Museum                10
Zoo                    7
Monument               7
Cave                   7
Wildlife Sanctuary     6
Monastery              5
Bird Sanctuary         4
Waterfall              4
Amusement Park         4
Park                   4
Temple                 4
Science                3
Lake                   3
Valley                 2
Landmark               2
Mausoleum              2
Cultural               2
Aquarium               1
Memorial               1
Orchard                1
Rock Carvings          1
Hill                   1
Religious Complex      1
Adventure Sport        1
Beach                  1
Natural Feature        1
Entertainment          1
Ski Resort             1
Tomb                   1
Prehistoric Site       1
Site                   1
Temples                1
Vineyard               1
Sculpture Garden       1
Cricket Ground         1
Tombs                  1
Film Studio            1


In [12]:
df = pd.get_dummies(df,dtype='int')

In [13]:
X = df.drop(columns = ['Entrance Fee in INR'])
Y = df['Entrance Fee in INR']

In [14]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.15)

In [15]:
X_train.shape

(120, 46)

In [16]:
Y_train.shape

(120,)

In [17]:
X_test.shape

(22, 46)

In [18]:
Y_test.shape

(22,)

In [19]:
model = LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [20]:
model.predict(X_test)

array([ 1.87500000e+01,  3.32500000e+01,  1.76088321e+15,  9.67000000e+02,
       -1.04092987e+15,  1.49500000e+02,  1.76088321e+15,  5.35000000e+01,
        1.11500000e+02,  4.52500000e+01,  9.07500000e+01,  1.13250000e+02,
        3.46500000e+02,  1.82500000e+01,  4.47500000e+01,  4.39750000e+02,
        1.22250000e+02,  7.51850000e+03,  3.42500000e+01,  1.30250000e+02,
        1.41000000e+02,  3.62500000e+01])

In [21]:
model.score(X_train,Y_train)

0.8593092372825499

In [22]:
model.score(X_test,Y_test)

-9.688962003141936e+24

In [23]:
model_las = Lasso(alpha = 0.1,max_iter = 1,tol = 0.001)
model_las.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.110e+06, tolerance: 8.426e+04
  model = cd_fast.enet_coordinate_descent(


Lasso(alpha=0.1, max_iter=1, tol=0.001)

In [24]:
model_las.predict(X_test)

array([ 2.68345957e+01,  3.81250859e+01,  2.04782776e+02,  1.00560154e+03,
        2.04450325e+02,  2.02514494e+02,  2.02687758e+02,  5.19560652e+01,
        1.10013424e+02,  3.88500671e+01, -2.95225081e+00,  9.75809469e+01,
        3.16065494e+02,  2.00208119e+01,  7.56072513e+01,  4.42620208e+02,
        9.17286602e+01,  7.49869767e+03, -3.77475946e+01,  8.77048498e+01,
        1.31691669e+02, -1.80717634e+01])

In [25]:
model_las.score(X_train,Y_train)

0.8578294691917485

In [26]:
model_las.score(X_test,Y_test)

-72.23912101101494

In [27]:
model_rid = Ridge(alpha = 0.1,max_iter = 1,tol = 0.001)
model_rid.fit(X_train,Y_train)

Ridge(alpha=0.1, max_iter=1, tol=0.001)

In [28]:
model_rid.score(X_train,Y_train)

0.8528914136280656

In [29]:
model_rid.score(X_test,Y_test)

-60.86692136411432

In [30]:
model_tree = DecisionTreeRegressor()
model_tree.fit(X_train,Y_train)

DecisionTreeRegressor()

In [31]:
model.predict(X_test)

array([ 1.87500000e+01,  3.32500000e+01,  1.76088321e+15,  9.67000000e+02,
       -1.04092987e+15,  1.49500000e+02,  1.76088321e+15,  5.35000000e+01,
        1.11500000e+02,  4.52500000e+01,  9.07500000e+01,  1.13250000e+02,
        3.46500000e+02,  1.82500000e+01,  4.47500000e+01,  4.39750000e+02,
        1.22250000e+02,  7.51850000e+03,  3.42500000e+01,  1.30250000e+02,
        1.41000000e+02,  3.62500000e+01])